### ISSUE TITLE
Problemas con coveralls

### ISSUE THREAD

**Issue by carlsjdh** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct05-objects-classes-interfaces-carlsjdh#1]
La configuración de `Github Actions` lo realiza correctamente sin embargo a la hora de subir el fichero a `coveralls` este aparece con un 0% cuando realmente debería salir un 76% cuando lo hice de forma manual (Sin las Github Action utilizando los tokens). Tuve que utilizar el parámetro `path-to-lcov` para especificar la localización del fichero ya que en mi caso el esquema de directorios separa código de documentación.
![image](https://user-images.githubusercontent.com/32093455/114319057-ba715d00-9b07-11eb-88ed-20893c91d711.png)

**Comment by carlsjdh** [comment]
@esegredo ¿Hay alguna forma de comprobar el fichero `lcov.info` que genera la máquina remota de Github Actions y poder depurar el problema?

**Comment by esegredo** [comment]
@carlsjdh si, claro. Añade un paso al workflow que te haga un cat de dicho fichero.
